### ISSUE TITLE
[doc] GREASY documentation as a website

### ISSUE THREAD

**Issue by victorusu** [BSC-Support-Team/GREASY#5]
I would like to propose that the GREASY documentation be converted into a website, similarly to the one that we have for [EESSI](https://github.com/EESSI/docs). This would allow for external contributors, like me, to also make documentation changes when proposing/introducing new features to the code. For instance, the "new" `@` syntax is not documented on the official GRESY [pdf user guide](https://github.com/BSC-Support-Team/GREASY/blob/master/doc/greasy_userguide.pdf).

I can do the initial work of setting up the documentation in web format, but still one needs to properly set the GREASY doc repo and make the appropriate initial configuration. I volunteer to make the full changes to the repo if you do not have the time for it. 

Please let me know what you think.

**Comment by PabloRodenas** [comment]
Dear Victor, 

I agree with the improvement of the documentation. It is an inherited user guide which dates from 2014 and before. I just found the original .odt file which generates the pdf. So I updated it with the @ syntax and it is already incorporated to git on its latest commit.

As you mentioned, in order to allow for external contributors to collaborate, and as we are already using markdown in other projects, we absolutely agree to go for it.

If you have the time to make the changes, we will be glad to adopt them and publish somewhere.

Thanks,

**Comment by PabloRodenas** [comment]
Dear Victor,

finally I got the time and I could convert the documentation to multimarkdown. On Monday I pushed my changes. It is published here:
https://www.bsc.es/user-support/greasy.php

Hope it is useful for you and if you have any comment or suggestion, please, let me know.

Best,
